# Generated by Django 4.2.5 on 2023-10-03 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_question_rank'),
        ('teacher', '0002_remove_pdfdocument_course_remove_pdfdocument_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='course',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, to='exam.course'),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
        ),
    ]
